### ISSUE TITLE
fixes to `get_gdrive_data()`

### ISSUE THREAD

**Issue by swnordstrom** [mikoontz/bristlecone-limber-drone-unmix#3]
Line 22, in the second assertion:

`sum(object %in% data_links$object) == 1`

Second line in this chunk - if trying to catch duplicates in the file, I think that logical statement inside `sum()` should be switched. `object %in% data_links$object` will always be length one (unless the length of `object` is greater than one, which I think shouldn't happen) whereas `data_links$object %in% object` will be the number of rows in `data_links`.

**Comment by swnordstrom** [comment]
Changing the issue to be more general changes to this function

The function as written won't read in the shape file I'm trying to read in. I think part of the issue is some confusion happening between `local_path` and `out_path` - `out_path` is what the function returns but can only be declared for `.zip` files.

**Comment by mikoontz** [comment]
Great catch on the order of the %in% assertion! I can patch that. Also good to be testing this on files that aren't .zip-- just looking at this on my phone, but doesn't line 96 set the out path to be equal to the local path when the extension isn't .zip?

**Comment by swnordstrom** [comment]
hmm - wasn't there on l96 when I looked. I added in something in that spot now. Both changes are made and pushed.
